import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    common: {
      appName: 'Smart Queue',
      language: 'Urdu',
      logout: 'Logout',
      loading: 'Loading...',
      submitting: 'Submitting...',
      success: 'Success',
      error: 'Error',
      home: 'Home',
    },
    splash: {
      tagline: 'Modern Queue Management System',
      loading: 'Initializing real-time connection...',
      connecting: 'Syncing live tokens & queue status...',
    },
    signOutModal: {
      badge: 'Security & Session',
      title: 'Confirm Sign Out',
      message: 'Are you sure you want to sign out?',
      submessage: 'You will return to the login screen. Any active tickets, tokens, and appointments remain safely preserved in the system.',
      confirm: 'Yes, Sign Out',
      cancel: 'Cancel / Stay',
    },
    welcome: {
      badge: 'Smart Healthcare Flow',
      title: 'Smart Queue',
      subtitle: 'Calm, intelligent digital patient flow management for modern healthcare clinics & hospitals.',
      getStarted: 'Get Started',
      continueDashboard: 'Continue to Dashboard',
      switchAccount: 'Sign in with another account',
      loggedInAs: 'Logged in as',
      clinicRole: 'Clinic',
      patientRole: 'Patient',
      zeroDelay: 'Zero Delay',
      liveTokens: 'Live Tokens',
      encrypted: 'Encrypted',
    },
    login: {
      title: 'Login',
      encryptedHealthPortal: 'Encrypted Health Portal',
      home: 'Home',
      appName: 'Smart Queue',
      brandFlow: 'Smart Healthcare Flow',
      realTimeBadge: 'Real-Time Queue Management',
      heading: 'Calm & Intelligent Patient Routing',
      desc: 'Minimize waiting stress with real-time digital token calling, estimated times, and live department tracking.',
      instantTokens: 'Instant Tokens',
      liveETAs: 'Live ETAs',
      encryptedSystem: 'Encrypted System',
      systemFooter: 'Smart Queue Management System',
      email: 'Email Address',
      emailPlaceholder: 'Enter email address',
      password: 'Password',
      passwordPlaceholder: 'Enter password',
      forgotPassword: 'Forgot Password?',
      button: 'Login',
      googleBtn: 'Continue with Google',
      noAccount: "Don't have an account?",
      registerHere: 'Register here',
      quickDemoFill: 'Quick Demo Fill',
      patient: 'Patient',
      clinic: 'Hospital / Clinic',
      invalidCreds: 'Invalid email or password.',
      loginSuccess: 'Logged in successfully!',
    },
    auth: {
      login: 'Login',
      register: 'Register',
      forgotPassword: 'Forgot Password?',
      email: 'Email Address',
      password: 'Password',
      googleBtn: 'Continue with Google',
      googleSignIn: 'Continue with Google',
      dontHaveAccount: "Don't have an account?",
      noAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      registerHere: 'Register here',
      loginHere: 'Login here',
      resetEmailSent: 'Password reset link sent to your email!',
      resetBtn: 'Send Reset Link',
      backToLogin: 'Back to Login',
      invalidCreds: 'Invalid email or password.',
      loginSuccess: 'Logged in successfully!',
      patientPortal: 'Patient Portal',
      clinicPortal: 'Clinic Portal',
      quickDemoFill: 'Quick Demo Fill',
      patient: 'Patient',
      clinic: 'Hospital / Clinic',
      encryptedHealthPortal: 'Encrypted Health Portal',
      calmIntelligentRouting: 'Calm & Intelligent Patient Routing',
      routingDesc: 'Minimize waiting stress with real-time digital token calling, estimated times, and live department tracking.',
      instantTokens: 'Instant Tokens',
      liveETAs: 'Live ETAs',
      encryptedSystem: 'Encrypted System',
      home: 'Home',
      smartHealthcareFlow: 'Smart Healthcare Flow',
    },
    register: {
      title: 'Create Account',
      badge: 'Live Patient & Clinic Registration',
      patientTab: 'Patient',
      orgTab: 'Hospital / Clinic',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Enter full name',
      email: 'Email Address',
      emailPlaceholder: 'Enter email address',
      phone: 'Phone Number',
      phonePlaceholder: 'Enter phone number',
      password: 'Password',
      passwordPlaceholder: 'Create a password',
      hospitalName: 'Hospital / Clinic Name',
      hospitalNamePlaceholder: 'Enter hospital or clinic name',
      address: 'Address / Location',
      addressPlaceholder: 'Enter clinic location / address',
      registerBtn: 'Register Account',
      backToLogin: 'Back to Login',
      alreadyHaveAccount: 'Already have an account?',
      loginHere: 'Login here',
      successPatient: 'Account created successfully! Redirecting to login...',
      successOrg: 'Clinic account created successfully! Redirecting to login...',
      emailInUse: 'This email is already registered. Please login or use a different email.',
    },
    forgotPassword: {
      title: 'Reset Password',
      badge: 'Direct Account Security',
      instructions: 'Enter your registered email address and your new password to update your account.',
      email: 'Registered Email Address',
      emailPlaceholder: 'Enter your registered email',
      newPassword: 'New Password',
      newPasswordPlaceholder: 'Enter your new password',
      sendBtn: 'Update Password & Continue to Login',
      backToLogin: 'Back to Login',
      successMsg: 'Password updated successfully! Redirecting to login...',
      userNotFound: 'No account found with this email. Please check and try again.',
    },
    patient: {
      dashboard: 'Patient Dashboard',
      welcome: 'Welcome back,',
      facilitySubtitle: 'Select your healthcare facility to join the live queue, check status, or get WhatsApp alerts.',
      selectFacilityLabel: 'Select Hospital / Clinic',
      selectFacilityPlaceholder: 'Select Healthcare Center',
      verified: 'Verified',
      bookToken: 'Book Token',
      walkIn: 'Walk-In',
      appointment: 'Scheduled Appointment',
      selectDept: 'Select Department',
      chooseDeptPlaceholder: 'Choose Department',
      selectDoc: 'Select Doctor (Optional)',
      bookingMode: 'Booking Mode',
      instantQueue: 'Instant Queue',
      doctorSlot: 'Doctor Slot',
      appointmentTime: 'Preferred Time (for Appointment)',
      emergencyBypass: 'Urgent / Critical Triage Bypass',
      emergencyBypassDesc: 'For chest pain, acute distress, or elderly emergency.',
      confirmEmergency: '🚨 Confirm Emergency Token',
      confirmBooking: 'Confirm Token Booking',
      liveQueue: 'Live Queue Status',
      activeToken: 'Your Active Token',
      emergencyPriorityBadge: '🚨 EMERGENCY PRIORITY TOKEN',
      showQrPass: 'Show Digital QR Pass',
      servingToken: 'Currently Serving',
      yourPosition: 'Your Queue Position',
      servingNow: 'Serving Now',
      positionTop: 'Position #1',
      estWait: 'Estimated Wait Time',
      mins: 'mins',
      zeroMins: '0 mins',
      reschedule: 'Reschedule Token',
      cancelToken: 'Cancel Token',
      noActiveToken: 'You do not have any active token right now.',
      waAlertsTitle: 'WhatsApp Live Queue Alerts',
      waAlertsDesc: 'Get automatic alerts on your WhatsApp as your turn approaches.',
      waFreeBadge: '100% Free Instant',
      waPhoneLabel: 'Your WhatsApp Phone Number',
      waPhonePlaceholder: '0300-1234567 or +923001234567',
      waSendBtn: 'Send WhatsApp Alert',
      waOpening: 'Opening WhatsApp...',
      allDeptsStatus: 'All Departments Status',
      servingPrefix: 'Serving:',
      waitingPrefix: 'Waiting:',
      avgWait: 'Avg Wait',
      noDeptsConfigured: 'No departments configured for this facility.',
      pastVisitsTitle: 'Past Visits & Token History',
      pastVisitsSub: 'Complete visit & appointment log for',
      totalRecords: 'Total Records',
      total: 'Total',
      visited: 'Visited',
      rescheduled: 'Rescheduled',
      cancelled: 'Cancelled',
      filterAll: 'All Records',
      filterVisited: 'Visited / Done',
      filterRescheduled: 'Rescheduled',
      filterCancelled: 'Cancelled',
      noRecordsFound: 'No visit records found for',
      walkinQueueTag: 'Walk-In Queue',
      appointmentTag: 'Scheduled Appointment',
      statusCompleted: 'Visited • Consultation Completed',
      statusCancelled: 'Cancelled by Patient',
      statusRescheduled: 'Rescheduled Slot',
      statusSkipped: 'Missed / No-Show',
      statusWaiting: 'Active in Queue',
      emergencyPriorityTag: '🚨 Emergency Priority',
      originalLabel: 'Original:',
      initialSlotLabel: 'Initial Slot',
      newLabel: 'New:',
      noteLabel: 'Note:',
      notifications: 'Real-time Notifications',
      noNotifications: 'No new notifications',
      feedback: 'Submit Feedback',
      rating: 'Rate your experience',
      comments: 'Share comments or suggestions...',
      submitFeedback: 'Submit Feedback',
      feedbackSuccess: 'Thank you for your feedback!',
      rescheduleSuccess: 'Token rescheduled successfully!',
      cancelSuccess: 'Token cancelled successfully!',
      bookedSuccess: 'Token booked successfully!',
      tokenBooked: 'Token booked successfully! Your Token is ',
      qrModalTitle: 'Digital Token Pass',
      generatingQr: 'Generating QR...',
      qrPatientLabel: 'Patient:',
      qrModalHint: "Show this QR code at the doctor's desk or triage reception for immediate fast-track check-in.",
      rescheduleModalTitle: 'Reschedule Token',
      chooseNewSlotLabel: 'Choose New Day & Time Slot',
      cancelBtn: 'Cancel',
      saveChanges: 'Save Changes',
      cancelConfirmTitle: 'Cancel Token',
      cancelConfirmDesc: 'Are you sure you want to cancel your queue position? This will be recorded in your past clinic history.',
      keepToken: 'Keep Token',
      confirmCancelBtn: 'Yes, Cancel',
    },
    org: {
      dashboard: 'Clinic Dashboard',
      welcome: 'Clinic Portal -',
      liveQueueMgmt: 'Live Queue Manager',
      advanceQueueHelp: 'Advance patient queue or skip absentees.',
      scanQrBtn: 'Scan QR',
      emergencyServingBadge: '🚨 EMERGENCY SERVING',
      noPatientServing: 'No patient in service',
      callNext: 'Call Next Patient',
      skipNoShow: 'Skip No-Show',
      waitingCountLabel: 'Waiting',
      servedCountLabel: 'Served',
      skippedCountLabel: 'Skipped',
      pleaseAddDept: 'Please add a department first.',
      patientsWaitingList: 'Patients Waiting List',
      colNo: 'No.',
      colPatient: 'Patient',
      colContact: 'Contact',
      colMode: 'Mode',
      colCheckIn: 'Check-in',
      colStatus: 'Status',
      urgentBadge: '🚨 Urgent',
      emergencyBypassTag: 'Emergency Bypass',
      priorityTopBadge: 'Priority Top',
      noPatientsWaiting: 'No patients waiting.',
      manualToken: 'Manual Token Generator',
      patientName: 'Patient Name',
      phone: 'Phone Number',
      selectDept: 'Select Department',
      emergencyBypassLabel: 'Emergency Priority Bypass',
      emergencyBypassHelp: 'Patient jumps to #1 waiting position immediately.',
      generateToken: 'Generate Token',
      issueEmergencyBtn: '🚨 Issue Emergency Token',
      deptLoad: 'Department Load Indicators',
      patientsWaiting: 'patients waiting',
      estWaitPrefix: 'Est. wait:',
      noDeptsActive: 'No departments active.',
      viewReports: 'View Analytics & Reports',
      manageDepts: 'Manage Departments',
      addDept: 'Add New Department',
      deptName: 'Department Name',
      avgServiceTime: 'Avg Service Time (mins)',
      addDeptBtn: 'Add Department',
      activeDeptsTitle: 'Active Departments',
      avgServiceLabel: 'Avg Service:',
      loadLabel: 'Load:',
      patientUnit: 'patient(s)',
      noActiveDepts: 'No active departments configured yet.',
      criticalSupplyAlert: 'Critical Supply Alert',
      belowThreshold: 'medical item(s) below safety threshold!',
      viewInventory: 'View Inventory',
      waRestockAlert: 'WhatsApp Restock Alert',
      totalTrackedItems: 'Total Tracked Items',
      optimalStockItems: 'Optimal Stock Items',
      lowStockAlerts: 'Low Stock Alerts',
      waRecipientTitle: 'Clinic WhatsApp Notification Recipient',
      waRecipientDesc: 'Automated restock alerts and emergency patient notices are routed here.',
      save: 'Save',
      opdInventoryTitle: 'OPD Medicines & Equipment Inventory',
      realtimeStockMonitor: 'Real-time Stock Monitor',
      colItemName: 'Item Name',
      colCategory: 'Category',
      colInStock: 'In Stock',
      colSafetyMin: 'Safety Min',
      colQuickAlert: 'Quick Alert',
      lowStockBadge: 'LOW STOCK',
      optimalBadge: 'Optimal',
      registerItemTitle: 'Register Medical Item',
      itemNameLabel: 'Item / Medicine Name',
      catMedicine: 'Medicine / Drug',
      catDisposable: 'OPD Disposable (Syringe, Gloves)',
      catEquipment: 'Clinical Equipment / Diagnostic',
      initialQtyLabel: 'Initial Qty',
      alertThresholdLabel: 'Alert Threshold',
      measuringUnitLabel: 'Measuring Unit',
      addToStockBtn: 'Add to Stock List',
      dailyForecastTitle: 'Daily Patient Load Forecast',
      aiConfidenceRate: 'AI Confidence',
      projectionsFor: 'Predictive Projections for',
      estimatedInflow: 'Estimated Inflow',
      patientsLabel: 'Patients',
      countersNeeded: 'counter(s) needed',
      aiStaffingTitle: 'AI Staffing & Crowd Optimization Recommendations',
      totalServed: 'Total Served Today',
      avgWaitTime: 'Avg Patient Wait Time',
      autoSkippedPatients: 'Auto-skipped Patients',
      peakHoursTitle: 'Historical Patient Inflow - Peak Hours Summary',
      morningSlot: 'Morning (9:00 AM - 12:00 PM)',
      afternoonSlot: 'Afternoon (12:00 PM - 3:00 PM)',
      eveningSlot: 'Evening (3:00 PM - 6:00 PM)',
      peakVolume: 'patient volume (Peak)',
      normalVolume: 'patient volume',
      qrScannerTitle: 'Scan / Verify Patient QR Token',
      qrScannerLabel: 'Enter or Scan QR Token Payload',
      qrScannerPlaceholder: 'Paste QR payload, token ID, or Token #',
      verifyTokenNow: 'Verify Token Now',
      tabQueue: 'Live Queue',
      tabDepartments: 'Departments',
      tabSupplies: 'Supplies',
      tabReports: 'Reports & AI',
      loadLow: 'Low Load',
      loadMedium: 'Medium Load',
      loadHigh: 'High Load',
      queueStatus: 'Queue status updated successfully!',
      patientCalled: 'Next patient called!',
      patientSkipped: 'Patient skipped (no-show).',
      deptAdded: 'Department added successfully!',
      deptDeleted: 'Department removed.',
      actions: 'Actions',
      status: 'Status',
      waiting: 'Waiting',
      serving: 'Serving',
      completed: 'Completed',
      skipped: 'Skipped',
    },
    scheduler: {
      selectDay: 'Select Appointment Day',
      today: 'Today',
      tomorrow: 'Tomorrow',
      pickFutureDate: 'Or pick a future date:',
      scheduledSlot: 'Scheduled Slot',
      recommendedSlots: 'Recommended Doctor Slots',
      quickOneTap: 'Quick 1-Tap',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
    },
    footer: {
      brand: 'Smart Queue Management System',
      liveSync: 'Real-Time Sync Active',
      encryptedBadge: '256-bit Encrypted Health Flow',
      allRights: 'All rights reserved.',
    }
  },
  ur: {
    common: {
      appName: 'اسمارٹ قطار',
      language: 'English',
      logout: 'لاگ آؤٹ',
      loading: 'لوڈنگ ہو رہی ہے...',
      submitting: 'جمع کروایا جا رہا ہے...',
      success: 'کامیابی',
      error: 'غلطی',
      home: 'ہوم پیج',
    },
    splash: {
      tagline: 'جدید ترین ڈیجیٹل قطار مینیجمنٹ سسٹم',
      loading: 'لائیو سسٹم سے رابطہ قائم کیا جا رہا ہے...',
      connecting: 'لائیو ٹوکن ڈیٹا ہم آہنگ ہو رہا ہے...',
    },
    signOutModal: {
      badge: 'سیشن مینیجمنٹ',
      title: 'لاگ آؤٹ کی تصدیق',
      message: 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
      submessage: 'آپ دوبارہ لاگ ان اسکرین پر چلے جائیں گے۔ آپ کے تمام فعال ٹوکنز اور تاریخ محفوظ رہے گی۔',
      confirm: 'جی ہاں، لاگ آؤٹ کریں',
      cancel: 'منسوخ کریں (ڈیش بورڈ پر رہیں)',
    },
    welcome: {
      badge: 'سمارٹ ہیلتھ کیئر فلو',
      title: 'اسمارٹ قطار',
      subtitle: 'جدید کلینکس اور ہسپتالوں کے لیے پرسکون، تیز اور منظم ڈیجیٹل قطار مینیجمنٹ نظام۔',
      getStarted: 'شروع کریں',
      continueDashboard: 'ڈیش بورڈ پر جائیں',
      switchAccount: 'کسی دوسرے اکاؤنٹ سے لاگ ان کریں',
      loggedInAs: 'لاگ ان بطور',
      clinicRole: 'کلینک',
      patientRole: 'مریض',
      zeroDelay: 'فوری سروس',
      liveTokens: 'لائیو ٹوکنز',
      encrypted: 'محفوظ نظام',
    },
    login: {
      title: 'لاگ ان',
      encryptedHealthPortal: 'محفوظ طبی پورٹل',
      home: 'ہوم پیج',
      appName: 'اسمارٹ قطار',
      brandFlow: 'سمارٹ ہیلتھ کیئر فلو',
      realTimeBadge: 'لائیو قطار مینیجمنٹ',
      heading: 'پرسکون اور منظم طبی سہولیات',
      desc: 'لائیو ٹوکن ٹریکنگ، متوقع انتظار کے وقت اور فوری ڈیجیٹل کالنگ کے ساتھ ہسپتال کے وقت کو آسان اور پرسکون بنائیں۔',
      instantTokens: 'فوری ٹوکن',
      liveETAs: 'لائیو اوقات',
      encryptedSystem: 'محفوظ نظام',
      systemFooter: 'اسمارٹ قطار مینیجمنٹ سسٹم',
      email: 'ای میل ایڈریس',
      emailPlaceholder: 'اپنا ای میل درج کریں',
      password: 'پاس ورڈ',
      passwordPlaceholder: 'اپنا پاس ورڈ درج کریں',
      forgotPassword: 'پاس ورڈ بھول گئے؟',
      button: 'لاگ ان کریں',
      googleBtn: 'گوگل کے ساتھ جاری رکھیں',
      noAccount: 'کیا آپ کا اکاؤنٹ نہیں ہے؟',
      registerHere: 'نیا اکاؤنٹ بنائیں',
      quickDemoFill: 'ڈیمو فوری لاگ ان',
      patient: 'مریض',
      clinic: 'ہسپتال / کلینک',
      invalidCreds: 'غلط ای میل یا پاس ورڈ درج کیا گیا ہے۔',
      loginSuccess: 'لاگ ان کامیاب رہا!',
    },
    auth: {
      login: 'لاگ ان کریں',
      register: 'رجسٹر کریں',
      forgotPassword: 'پاس ورڈ بھول گئے؟',
      email: 'ای میل ایڈریس',
      password: 'پاس ورڈ',
      googleBtn: 'گوگل کے ساتھ جاری رکھیں',
      googleSignIn: 'گوگل کے ساتھ جاری رکھیں',
      dontHaveAccount: 'کیا آپ کا اکاؤنٹ نہیں ہے؟',
      noAccount: 'کیا آپ کا اکاؤنٹ نہیں ہے؟',
      alreadyHaveAccount: 'پہلے سے اکاؤنٹ موجود ہے؟',
      registerHere: 'یہاں رجسٹر کریں',
      loginHere: 'یہاں لاگ ان کریں',
      resetEmailSent: 'پاس ورڈ دوبارہ ترتیب دینے کا لنک ای میل کر دیا گیا ہے!',
      resetBtn: 'ری سیٹ لنک بھیجیں',
      backToLogin: 'لاگ ان پر واپس جائیں',
      invalidCreds: 'غلط ای میل یا پاس ورڈ درج کیا گیا ہے۔',
      loginSuccess: 'لاگ ان کامیاب رہا!',
      patientPortal: 'مریض پورٹل',
      clinicPortal: 'کلینک پورٹل',
      quickDemoFill: 'ڈیمو فوری لاگ ان',
      patient: 'مریض',
      clinic: 'ہسپتال / کلینک',
      encryptedHealthPortal: 'محفوظ طبی پورٹل',
      calmIntelligentRouting: 'پرسکون اور منظم طبی سہولیات',
      routingDesc: 'لائیو ٹوکن ٹریکنگ اور انتظار کے متوقع وقت کے ساتھ طبی معائنے کو آسان اور پرسکون بنائیں۔',
      instantTokens: 'فوری ٹوکن',
      liveETAs: 'لائیو اوقات',
      encryptedSystem: 'محفوظ نظام',
      home: 'ہوم پیج',
      smartHealthcareFlow: 'سمارٹ ہیلتھ کیئر فلو',
    },
    register: {
      title: 'نیا اکاؤنٹ بنائیں',
      badge: 'لائیو مریض اور کلینک رجسٹریشن پورٹل',
      patientTab: 'مریض',
      orgTab: 'ہسپتال / کلینک',
      fullName: 'پورا نام',
      fullNamePlaceholder: 'اپنا مکمل نام درج کریں',
      email: 'ای میل ایڈریس',
      emailPlaceholder: 'اپنا ای میل درج کریں',
      phone: 'فون نمبر',
      phonePlaceholder: 'اپنا فون نمبر درج کریں',
      password: 'پاس ورڈ',
      passwordPlaceholder: 'محفوظ پاس ورڈ درج کریں',
      hospitalName: 'ہسپتال یا کلینک کا نام',
      hospitalNamePlaceholder: 'ہسپتال یا کلینک کا نام درج کریں',
      address: 'پتہ یا مقام',
      addressPlaceholder: 'کلینک کا پتہ درج کریں',
      registerBtn: 'اکاؤنٹ بنائیں',
      backToLogin: 'لاگ ان پر واپس',
      alreadyHaveAccount: 'پہلے سے اکاؤنٹ موجود ہے؟',
      loginHere: 'یہاں لاگ ان کریں',
      successPatient: 'اکاؤنٹ کامیابی سے بن گیا! لاگ ان پیج پر بھیجا جا رہا ہے...',
      successOrg: 'کلینک کا اکاؤنٹ بن گیا! لاگ ان پیج پر بھیجا جا رہا ہے...',
      emailInUse: 'یہ ای میل پہلے سے رجسٹرڈ ہے۔ براہ کرم لاگ ان کریں یا دوسری ای میل درج کریں۔',
    },
    forgotPassword: {
      title: 'پاس ورڈ تبدیل کریں',
      badge: 'محفوظ اکاؤنٹ بحالی',
      instructions: 'اپنا رجسٹرڈ ای میل ایڈریس اور نیا پاس ورڈ درج کریں تاکہ آپ کے اکاؤنٹ کا پاس ورڈ تبدیل ہو سکے۔',
      email: 'رجسٹرڈ ای میل ایڈریس',
      emailPlaceholder: 'اپنا رجسٹرڈ ای میل درج کریں',
      newPassword: 'نیا پاس ورڈ',
      newPasswordPlaceholder: 'اپنا نیا پاس ورڈ درج کریں',
      sendBtn: 'پاس ورڈ تبدیل کر کے لاگ ان پر جائیں',
      backToLogin: 'لاگ ان پر واپس',
      successMsg: 'پاس ورڈ کامیابی سے تبدیل ہو گیا! لاگ ان پیج پر منتقل کیا جا رہا ہے...',
      userNotFound: 'اس ای میل سے کوئی اکاؤنٹ موجود نہیں ہے۔ براہ کرم دوبارہ چیک کریں۔',
    },
    patient: {
      dashboard: 'مریض کا ڈیش بورڈ',
      welcome: 'خوش آمدید،',
      facilitySubtitle: 'لائیو قطار میں شامل ہونے، کیفیت جانچنے یا واٹس ایپ الرٹس کے لیے ہسپتال منتخب کریں۔',
      selectFacilityLabel: 'ہسپتال یا کلینک منتخب کریں',
      selectFacilityPlaceholder: 'ہیلتھ کیئر سنٹر کا انتخاب کریں',
      verified: 'تصدیق شدہ',
      bookToken: 'ٹوکن حاصل کریں',
      walkIn: 'عام وزٹ (واک ان)',
      appointment: 'پہلے سے طے شدہ ملاقات',
      selectDept: 'شعبہ منتخب کریں',
      chooseDeptPlaceholder: 'شعبہ منتخب کریں',
      selectDoc: 'ڈاکٹر منتخب کریں (اختیاری)',
      bookingMode: 'بکنگ کا طریقہ کار',
      instantQueue: 'فوری قطار',
      doctorSlot: 'ڈاکٹر کا وقت',
      appointmentTime: 'پسندیدہ وقت (ملاقات کے لیے)',
      emergencyBypass: 'ہنگامی / فوری طبی امداد (ایمرجنسی)',
      emergencyBypassDesc: 'سینے میں درد، شدید تکلیف یا ہنگامی حالت کے لیے۔',
      confirmEmergency: '🚨 ایمرجنسی ٹوکن جاری کریں',
      confirmBooking: 'ٹوکن بکنگ کی تصدیق کریں',
      liveQueue: 'قطار کی تازہ ترین صورتحال',
      activeToken: 'آپ کا فعال ٹوکن',
      emergencyPriorityBadge: '🚨 ایمرجنسی ترجیحی ٹوکن',
      showQrPass: 'ڈیجیٹل کیو آر پاس دکھائیں',
      servingToken: 'زیر معائنہ ٹوکن',
      yourPosition: 'آپ کا نمبر',
      servingNow: 'ابھی باری ہے',
      positionTop: 'پہلا نمبر',
      estWait: 'انتظار کا متوقع وقت',
      mins: 'منٹ',
      zeroMins: '0 منٹ',
      reschedule: 'ٹوکن کا وقت بدلیں',
      cancelToken: 'ٹوکن منسوخ کریں',
      noActiveToken: 'آپ کا کوئی فعال ٹوکن نہیں ہے۔',
      waAlertsTitle: 'واٹس ایپ لائیو الرٹس',
      waAlertsDesc: 'اپنی باری قریب آنے پر واٹس ایپ پر فوری الرٹس حاصل کریں۔',
      waFreeBadge: 'فوری اور مفت',
      waPhoneLabel: 'اپنا واٹس ایپ فون نمبر',
      waPhonePlaceholder: '0300-1234567 یا 03001234567',
      waSendBtn: 'واٹس ایپ الرٹ بھیجیں',
      waOpening: 'واٹس ایپ کھولا جا رہا ہے...',
      allDeptsStatus: 'تمام شعبہ جات کی صورتحال',
      servingPrefix: 'موجودہ باری:',
      waitingPrefix: 'انتظار میں:',
      avgWait: 'اوسط انتظار',
      noDeptsConfigured: 'اس ہسپتال میں ابھی کوئی شعبہ موجود نہیں ہے۔',
      pastVisitsTitle: 'سابقہ وزٹس اور ٹوکن ہسٹری',
      pastVisitsSub: 'مکمل وزٹ اور اپائنٹمنٹ لاگ برائے',
      totalRecords: 'کل ریکارڈز',
      total: 'کل',
      visited: 'معائنہ شدہ',
      rescheduled: 'وقت تبدیل',
      cancelled: 'منسوخ شدہ',
      filterAll: 'تمام ریکارڈز',
      filterVisited: 'معائنہ مکمل',
      filterRescheduled: 'وقت تبدیل شدہ',
      filterCancelled: 'منسوخ شدہ',
      noRecordsFound: 'کوئی وزٹ ریکارڈ نہیں ملا برائے',
      walkinQueueTag: 'عام قطار (واک ان)',
      appointmentTag: 'پہلے سے طے شدہ ملاقات',
      statusCompleted: 'وزٹ مکمل • معائنہ ہو گیا',
      statusCancelled: 'مریض نے منسوخ کیا',
      statusRescheduled: 'وقت تبدیل شدہ',
      statusSkipped: 'غیر حاضر',
      statusWaiting: 'قطار میں موجود',
      emergencyPriorityTag: '🚨 ایمرجنسی ترجیح',
      originalLabel: 'پہلا وقت:',
      initialSlotLabel: 'ابتدائی وقت',
      newLabel: 'نیا وقت:',
      noteLabel: 'نوٹ:',
      notifications: 'حالیہ اطلاعات',
      noNotifications: 'کوئی نئی اطلاع نہیں ہے',
      feedback: 'فیڈ بیک فارم',
      rating: 'اپنے تجربے کی درجہ بندی کریں',
      comments: 'اپنی رائے یا تجاویز لکھیں...',
      submitFeedback: 'رائے جمع کروائیں',
      feedbackSuccess: 'آپ کی رائے کا بہت شکریہ!',
      rescheduleSuccess: 'ٹوکن کا وقت کامیابی سے تبدیل ہو گیا ہے!',
      cancelSuccess: 'ٹوکن منسوخ کر دیا گیا ہے!',
      bookedSuccess: 'ٹوکن کامیابی سے بک ہو گیا ہے!',
      tokenBooked: 'ٹوکن بک ہو گیا ہے! آپ کا ٹوکن نمبر ہے ',
      qrModalTitle: 'ڈیجیٹل ٹوکن پاس',
      generatingQr: 'کیو آر کوڈ تیار ہو رہا ہے...',
      qrPatientLabel: 'مریض:',
      qrModalHint: 'ڈاکٹر کے کاؤنٹر یا استقبالیہ پر فوری چیک ان کے لیے یہ کیو آر کوڈ دکھائیں۔',
      rescheduleModalTitle: 'ٹوکن کا وقت تبدیل کریں',
      chooseNewSlotLabel: 'نیا دن اور وقت منتخب کریں',
      cancelBtn: 'منسوخ',
      saveChanges: 'تبدیلی محفوظ کریں',
      cancelConfirmTitle: 'ٹوکن منسوخ کریں',
      cancelConfirmDesc: 'کیا آپ واقعی اپنا قطار کا نمبر منسوخ کرنا چاہتے ہیں؟ یہ آپ کی ہسٹری میں محفوظ ہوگا۔',
      keepToken: 'ٹوکن برقرار رکھیں',
      confirmCancelBtn: 'جی ہاں، منسوخ کریں',
    },
    org: {
      dashboard: 'کلینک کا ڈیش بورڈ',
      welcome: 'کلینک پورٹل -',
      liveQueueMgmt: 'قطار کا انتظام',
      advanceQueueHelp: 'قطار آگے بڑھائیں یا غیر حاضر مریض کو چھوڑیں۔',
      scanQrBtn: 'کیو آر اسکین کریں',
      emergencyServingBadge: '🚨 ایمرجنسی مریض زیر معائنہ',
      noPatientServing: 'کوئی مریض زیر معائنہ نہیں ہے',
      callNext: 'اگلے مریض کو بلائیں',
      skipNoShow: 'غیر حاضر کو چھوڑیں',
      waitingCountLabel: 'انتظار میں',
      servedCountLabel: 'معائنہ شدہ',
      skippedCountLabel: 'چھوڑ دیا',
      pleaseAddDept: 'براہ کرم پہلے کوئی شعبہ شامل کریں۔',
      patientsWaitingList: 'انتظار کرنے والے مریضوں کی فہرست',
      colNo: 'نمبر',
      colPatient: 'مریض',
      colContact: 'رابطہ',
      colMode: 'طریقہ کار',
      colCheckIn: 'آمد کا وقت',
      colStatus: 'حالت',
      urgentBadge: '🚨 فوری / ہنگامی',
      emergencyBypassTag: 'ایمرجنسی بائی پاس',
      priorityTopBadge: 'اولین ترجیح',
      noPatientsWaiting: 'کوئی مریض انتظار میں نہیں ہے۔',
      manualToken: 'دستی ٹوکن کا اجراء',
      patientName: 'مریض کا نام',
      phone: 'فون نمبر',
      selectDept: 'شعبہ منتخب کریں',
      emergencyBypassLabel: 'ہنگامی ترجیحی بائی پاس',
      emergencyBypassHelp: 'مریض فوری طور پر قطار میں پہلے نمبر پر آ جائے گا۔',
      generateToken: 'ٹوکن بنائیں',
      issueEmergencyBtn: '🚨 ایمرجنسی ٹوکن جاری کریں',
      deptLoad: 'شعبہ جات پر رش کی صورتحال',
      patientsWaiting: 'مریض انتظار میں ہیں',
      estWaitPrefix: 'متوقع انتظار:',
      noDeptsActive: 'کوئی شعبہ فعال نہیں ہے۔',
      viewReports: 'رپورٹس اور تجزیہ',
      manageDepts: 'شعبہ جات کا انتظام',
      addDept: 'نیا شعبہ شامل کریں',
      deptName: 'شعبہ کا نام',
      avgServiceTime: 'اوسط معائنہ کا وقت (منٹ)',
      addDeptBtn: 'شعبہ شامل کریں',
      activeDeptsTitle: 'فعال شعبہ جات',
      avgServiceLabel: 'اوسط وقت:',
      loadLabel: 'رش:',
      patientUnit: 'مریض',
      noActiveDepts: 'ابھی تک کوئی فعال شعبہ ترتیب نہیں دیا گیا۔',
      criticalSupplyAlert: 'طبی سامان کی کمی کا الرٹ',
      belowThreshold: 'طبی آئٹمز کی مقدار کم از کم حد سے کم ہے!',
      viewInventory: 'اسٹاک لسٹ دیکھیں',
      waRestockAlert: 'واٹس ایپ پر آرڈر بھیجیں',
      totalTrackedItems: 'کل رجسٹرڈ سامان',
      optimalStockItems: 'مکمل اسٹاک والے آئٹمز',
      lowStockAlerts: 'کم اسٹاک کے الرٹس',
      waRecipientTitle: 'کلینک واٹس ایپ وصول کنندہ',
      waRecipientDesc: 'سامان کی کمی کے الرٹس اور ایمرجنسی اطلاعات یہاں موصول ہوں گی۔',
      save: 'محفوظ کریں',
      opdInventoryTitle: 'او پی ڈی ادویات اور آلات کا اسٹاک',
      realtimeStockMonitor: 'لائیو اسٹاک مانیٹر',
      colItemName: 'چیز کا نام',
      colCategory: 'قسم',
      colInStock: 'موجود مقدار',
      colSafetyMin: 'کم از کم حد',
      colQuickAlert: 'فوری الرٹ',
      lowStockBadge: 'اسٹاک کم ہے',
      optimalBadge: 'مناسب مقدار',
      registerItemTitle: 'نیا طبی سامان درج کریں',
      itemNameLabel: 'دوا یا سامان کا نام',
      catMedicine: 'دوا (میڈیسن)',
      catDisposable: 'استعمال شدہ سامان (سرنج، دستانے وغیرہ)',
      catEquipment: 'طبی آلات و ڈائیگنوسٹک',
      initialQtyLabel: 'ابتدائی مقدار',
      alertThresholdLabel: 'الرٹ کی حد',
      measuringUnitLabel: 'پیمائش کی اکائی (باکس / پیک)',
      addToStockBtn: 'اسٹاک میں شامل کریں',
      dailyForecastTitle: 'مریضوں کی متوقع آمد کا تخمینہ',
      aiConfidenceRate: 'اے آئی کا اعتمادی تناسب',
      projectionsFor: 'متوقع پیشین گوئی برائے',
      estimatedInflow: 'متوقع مریضوں کی آمد',
      patientsLabel: 'مریض',
      countersNeeded: 'کاؤنٹر درکار ہیں',
      aiStaffingTitle: 'اے آئی عملہ و رش کنٹرول تجاویز',
      totalServed: 'آج کل مریضوں کی تعداد',
      avgWaitTime: 'مریضوں کا اوسط انتظار کا وقت',
      autoSkippedPatients: 'غیر حاضر رہ جانے والے مریض',
      peakHoursTitle: 'رش کے اوقات کا خلاصہ',
      morningSlot: 'صبح (9:00 بجے تا 12:00 بجے)',
      afternoonSlot: 'دوپہر (12:00 بجے تا 3:00 بجے)',
      eveningSlot: 'شام (3:00 بجے تا 6:00 بجے)',
      peakVolume: 'مریضوں کا تناسب (سب سے زیادہ رش)',
      normalVolume: 'مریضوں کا تناسب',
      qrScannerTitle: 'مریض کا کیو آر ٹوکن تصدیق کریں',
      qrScannerLabel: 'کیو آر کوڈ یا ٹوکن نمبر درج کریں',
      qrScannerPlaceholder: 'کیو آر ڈیٹا یا ٹوکن نمبر درج کریں',
      verifyTokenNow: 'ابھی تصدیق کریں',
      tabQueue: 'لائیو قطار',
      tabDepartments: 'شعبہ جات',
      tabSupplies: 'طبی سامان اور ادویات',
      tabReports: 'رپورٹس اور اے آئی',
      loadLow: 'کم رش',
      loadMedium: 'درمیانہ رش',
      loadHigh: 'زیادہ رش',
      queueStatus: 'قطار کی صورتحال اپ ڈیٹ کر دی گئی ہے!',
      patientCalled: 'اگلے مریض کو آواز دی گئی ہے!',
      patientSkipped: 'مریض کو غیر حاضر قرار دے کر چھوڑ دیا گیا ہے۔',
      deptAdded: 'نیا شعبہ کامیابی سے شامل ہو گیا ہے!',
      deptDeleted: 'شعبہ ختم کر دیا گیا ہے۔',
      actions: 'کارروائی',
      status: 'حالت',
      waiting: 'انتظار میں',
      serving: 'زیر معائنہ',
      completed: 'مکمل',
      skipped: 'چھوڑ دیا',
    },
    scheduler: {
      selectDay: 'ملاقات کا دن منتخب کریں',
      today: 'آج',
      tomorrow: 'کل',
      pickFutureDate: 'یا کوئی اگلی تاریخ منتخب کریں:',
      scheduledSlot: 'مقررہ وقت',
      recommendedSlots: 'تجویز کردہ اوقات',
      quickOneTap: 'فوری انتخاب',
      morning: 'صبح',
      afternoon: 'دوپہر',
      evening: 'شام',
    },
    footer: {
      brand: 'اسمارٹ قطار مینیجمنٹ سسٹم',
      liveSync: 'لائیو ڈیٹا ہم آہنگی فعال ہے',
      encryptedBadge: '256 بٹ محفوظ ہیلتھ فلو',
      allRights: 'جملہ حقوق محفوظ ہیں۔',
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState(() => {
    return localStorage.getItem('queue_lang') || 'en';
  });

  const toggleLanguage = () => {
    const nextLocale = locale === 'en' ? 'ur' : 'en';
    setLocale(nextLocale);
    localStorage.setItem('queue_lang', nextLocale);
  };

  const t = (keyPath) => {
    const keys = keyPath.split('.');
    let value = translations[locale];
    for (const key of keys) {
      if (value && value[key] !== undefined) {
        value = value[key];
      } else {
        // Fallback to English if translation is missing in current locale
        let fallback = translations.en;
        for (const fbKey of keys) {
          if (fallback && fallback[fbKey] !== undefined) {
            fallback = fallback[fbKey];
          } else {
            return keyPath;
          }
        }
        return fallback;
      }
    }
    return value;
  };

  // Synchronize document attributes safely without breaking viewport horizontal slider coordinates
  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.setAttribute('data-locale', locale);
    
    // Crucial: Keep documentElement.dir as 'ltr' so absolute/sliding viewport coordinates
    // (e.g. 200vw stage track, translate3d(-100vw, 0, 0)) never shift or push cards off-screen.
    // RTL direction is cleanly applied to individual cards/sections via dir={locale === 'ur' ? 'rtl' : 'ltr'}.
    document.documentElement.dir = 'ltr';

    if (locale === 'ur') {
      document.documentElement.classList.add('lang-ur');
      document.body.classList.add('lang-ur');
    } else {
      document.documentElement.classList.remove('lang-ur');
      document.body.classList.remove('lang-ur');
    }
  }, [locale]);

  return (
    <LanguageContext.Provider value={{ locale, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
